apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: app-name
    version: stable
  name: app-name
spec:
  selector:
    matchLabels:
      app: app-name
      version: stable
  template:
    metadata:
      labels:
        app: app-name
        version: stable
    spec:
      containers:
      - image: container-image:latest
        name: container
      imagePullSecrets:
      - name: regcred
